name: "[develop] PR label"

on:
  pull_request:
    branches:
      - develop
    types:
      - labeled
      - reopened
      - unlabeled

jobs:
  check_label:
    name: "Check label"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Validate label
        uses: mheap/github-action-required-labels@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          mode: exactly
          count: 1
          labels: "major, minor, patch"
