name: "[develop] PR open"

on:
  pull_request:
    branches:
      - develop
    types:
      - opened
      - synchronize

jobs:
  request_versioning_label:
    name: "Request versioning label"
    if: github.event.action == 'opened'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Add comment
        uses: mshick/add-pr-comment@v1
        with:
          message: Please assign a versioning label to the pull request, using either 'major', 'minor', or 'patch'.
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  quality_assurance_check:
    name: "Quality assurance check"
    if: contains(fromJson('["opened", "synchronize"]'), github.event.action)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure environment
        uses: actions/setup-node@v4
        with:
          node-version: "20.13.1"
          cache: "npm"
          cache-dependency-path: "examples/node-js/design-system"
      - name: Install dependencies
        run: npm install
        working-directory: examples/node-js/design-system
      - name: Execute unit tests
        run: npm run unit:tests
        working-directory: examples/node-js/design-system
      - name: Execute integration tests
        run: npm run integration:tests
        working-directory: examples/node-js/design-system
