name: "[develop] PR open"

on:
  pull_request:
    branches:
      - develop
    types:
      - opened
      - synchronize

jobs:
  request_versioning_label:
    name: "Request versioning label"
    if: github.event.action == 'opened'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Add comment
        uses: mshick/add-pr-comment@v1
        with:
          message: Please assign a versioning label to the pull request, using either 'major', 'minor', or 'patch'.
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  setup_environment:
    name: "Configure node.js environment"
    if: contains(fromJson('["opened", "synchronize"]'), github.event.action)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure environment
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "examples/node-js/design-system"
      - name: Install dependencies
        run: npm install
        working-directory: examples/node-js/design-system
      - name: Upload dependencies
        uses: actions/upload-artifact@v3
        with:
          name: node-modules
          path: examples/node-js/design-system/node_modules

  run_unit_tests:
    name: "Run unit tests"
    needs: setup_environment
    if: contains(fromJson('["opened", "synchronize"]'), github.event.action)
    runs-on: ubuntu-latest
    steps:
      - name: Download Node.js dependencies
        uses: actions/download-artifact@v3
        with:
          name: node-modules
      - name: Execute unit tests
        run: ls -la
      - name: Execute unit tests 2
        run: pwd

  run_integration_tests:
    name: "Run integration tests"
    needs: run_unit_tests
    if: contains(fromJson('["opened", "synchronize"]'), github.event.action)
    runs-on: ubuntu-latest
    steps:
      - name: Download Node.js dependencies
        uses: actions/download-artifact@v3
        with:
          name: node-modules
      - name: Execute integration tests
        run: npm run integration:tests
